spring:
  main.allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate.ddl-auto: none
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    enabled: true

